server:
  host: "localhost"
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  shutdown_timeout: 10s

logging:
  level: "info"
  format: "json"
  output: "stdout"

game:
  max_players: 1000
  save_interval: 30s
  cleanup_interval: 5m
  session_timeout: 1h

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"

database:
  driver: "sqlite"
  source: "game.db"
  max_connections: 25
  max_idle_connections: 25
  connection_lifetime: 5m

metrics:
  enabled: true
  path: "/metrics"

health:
  enabled: true
  path: "/health"